package modelo.pojo;
// Generated 01-jun-2015 18:19:23 by Hibernate Tools 3.6.0



/**
 * Amigo generated by hbm2java
 */
public class Amigo  implements java.io.Serializable {


     private int id;
     private int idSeguidor;
     private int idSeguido;

    public Amigo() {
    }

    public Amigo(int id, int idSeguidor, int idSeguido) {
       this.id = id;
       this.idSeguidor = idSeguidor;
       this.idSeguido = idSeguido;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getIdSeguidor() {
        return this.idSeguidor;
    }
    
    public void setIdSeguidor(int idSeguidor) {
        this.idSeguidor = idSeguidor;
    }
    public int getIdSeguido() {
        return this.idSeguido;
    }
    
    public void setIdSeguido(int idSeguido) {
        this.idSeguido = idSeguido;
    }




}


