package modelo.pojo;
// Generated 01-jun-2015 18:19:23 by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Evento generated by hbm2java
 */
public class Evento  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private Date fecha;
     private String lugar;
     private String descripcion;
     private int userCreador;
     private int categoria;

    public Evento() {
    }

    public Evento(String nombre, Date fecha, String lugar, String descripcion, int userCreador, int categoria) {
       this.nombre = nombre;
       this.fecha = fecha;
       this.lugar = lugar;
       this.descripcion = descripcion;
       this.userCreador = userCreador;
       this.categoria = categoria;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getLugar() {
        return this.lugar;
    }
    
    public void setLugar(String lugar) {
        this.lugar = lugar;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public int getUserCreador() {
        return this.userCreador;
    }
    
    public void setUserCreador(int userCreador) {
        this.userCreador = userCreador;
    }
    public int getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(int categoria) {
        this.categoria = categoria;
    }




}


