package modelo.pojo;
// Generated 01-jun-2015 18:19:23 by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * MensajePrivado generated by hbm2java
 */
public class MensajePrivado  implements java.io.Serializable {


     private Integer id;
     private String texto;
     private Date fecha;
     private int idEmisor;
     private int idReceptor;

    public MensajePrivado() {
    }

    public MensajePrivado(String texto, Date fecha, int idEmisor, int idReceptor) {
       this.texto = texto;
       this.fecha = fecha;
       this.idEmisor = idEmisor;
       this.idReceptor = idReceptor;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getTexto() {
        return this.texto;
    }
    
    public void setTexto(String texto) {
        this.texto = texto;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public int getIdEmisor() {
        return this.idEmisor;
    }
    
    public void setIdEmisor(int idEmisor) {
        this.idEmisor = idEmisor;
    }
    public int getIdReceptor() {
        return this.idReceptor;
    }
    
    public void setIdReceptor(int idReceptor) {
        this.idReceptor = idReceptor;
    }




}


